# Generated by Django 2.0.5 on 2018-05-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(default=0, verbose_name='Giá')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('color', models.CharField(max_length=50, verbose_name='Màu')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('description', models.TextField(verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('hash', models.CharField(editable=False, max_length=200, verbose_name='hash')),
                ('previousHash', models.CharField(editable=False, max_length=200, verbose_name='previoushash')),
                ('timeStamp', models.IntegerField(default=0, editable=False, verbose_name='timestamp')),
            ],
            bases=('core.product',),
        ),
    ]
